/**
 * Books I am reading in 2026 – curated list data.
 * Source: https://gist.github.com/von-steinkirch/abceab872b7a4bab220e64230f92a66a
 */
const BOOKS_2026 = {
    title: 'books i am reading in 2026',
    shareId: 'books-2026',
    sourceUrl: 'https://gist.github.com/von-steinkirch/abceab872b7a4bab220e64230f92a66a',
    months: [
        {
            id: 'august',
            label: 'august',
            count: 4,
            books: [
                { title: 'cosmos (carl sagan)', rating: '9.9/10', url: 'https://gist.github.com/von-steinkirch/05851c6268dc569b9281c9c57662ec27', note: 'my thoughts' },
                { title: 'the virtue of selfishness (ayn rand)', rating: '9.9/10', url: 'https://gist.github.com/von-steinkirch/7b18ffc28983e015de7a8f32ddfaa0a3', note: 'my thoughts' },
                { title: 'the saying of confucious', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/1b7449fc68b3a148a0fceb36768eed4f', note: 'my thoughts' },
                { title: 'the denial of death (ernest becker)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/e9acac56479421576b23173be663b6f6', note: 'my thoughts' },
            ]
        },
        {
            id: 'july',
            label: 'july',
            count: 5,
            books: [
                { title: 'superintelligence (nick bostrom)', rating: '10/10', url: 'https://marina.nullstar.fun/pages/post.html?post=book_superintel', note: 'my thoughts' },
                { title: 'the tale of genji (murasaki shikibu)', rating: '(unfinished)', note: 'another time <3' },
                { title: 'neuromancer (william gibson)', rating: '7/10' },
                { title: 'the obstacle is the way (ryan holiday)', rating: '9/10', url: 'https://gist.github.com/von-steinkirch/13a135cca8097caa3126d1b6ce6e9f4a', note: 'my thoughts' },
                { title: 'the singularity is near (ray kurzweil)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/31c1545bc212c091d77e2c5b111328e3', note: 'my thoughts' },
            ]
        },
        {
            id: 'june',
            label: 'june',
            count: 1,
            books: [
                { title: 'the prince (machiavelli)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/80e3397c4619111d5e8da2cef3c3d9ed', note: 'my thoughts' },
            ]
        },
        {
            id: 'may',
            label: 'may',
            count: 4,
            books: [
                { title: 'the lean startup (eric ries)', rating: '7/10', url: 'https://gist.github.com/von-steinkirch/3fb77a84eacb36d4a8642fa73bd22030', note: 'my thoughts' },
                { title: 'hagakure: book of the samurai (yamamoto tsunetomo)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/1eed70049ed6c41ad8c65f7883d13430', note: 'my thoughts' },
                { title: 'ethics (spinoza)', rating: '7/10' },
                { title: 'the psychology of persuasion (robert b. cialdini)', rating: '7/10 (unfinished)' },
            ]
        },
        {
            id: 'april',
            label: 'april',
            count: 2,
            books: [
                { title: 'pirkei avot', rating: '8/10' },
                { title: 'the republic (plato)', rating: '8/10' },
            ]
        },
        {
            id: 'march',
            label: 'march',
            count: 4,
            books: [
                { title: 'abundance (ezra klein & derek thompson)', rating: '6/10' },
                { title: 'the rational optimist (matt ridley)', rating: '7/10' },
                { title: 'compensation (ralph waldo emerson)', rating: '7/10' },
                { title: 'calendar of wisdom (leo tolstoy)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/b00b90d17d17a218fd660df8c9166ec9', note: 'my thoughts' },
            ]
        },
        {
            id: 'february',
            label: 'february',
            count: 7,
            books: [
                { title: 'the stranger (albert camus)', rating: '7/10', url: 'https://gist.github.com/von-steinkirch/e385326a51ec639dbf25e1563f7436da', note: 'my thoughts' },
                { title: 'the fall (albert camus)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/d498090050c4523777d9f02ef3eee5f3', note: 'my thoughts' },
                { title: 'the symbolic species (terrence w. deacon)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/996eeae70ea700f7de54cdf91e39cc31', note: 'my thoughts' },
                { title: 'yes to life (viktor frankl)', rating: '8/10', url: 'https://gist.github.com/von-steinkirch/edfd956297c66f7ce2734370391b3c0d', note: 'my thoughts' },
                { title: 'nausea (jean-paul sartre)', rating: '7/10', note: '"life begins on the other side of despair."' },
                { title: 'the code of the woosters (p.g. wodehouse)', rating: '7/10' },
                { title: 'at the mountains of madness (h.p. lovecraft)', rating: '6/10', note: 'a classic, but a lil boring for "2026\'s marina".' },
            ]
        },
        {
            id: 'january',
            label: 'january',
            count: 7,
            books: [
                { title: 'meditations (marcus aurelius)', rating: '10/10', url: 'https://gist.github.com/von-steinkirch/038cccccd1d428a3deca69080c300276', note: 'my thoughts' },
                { title: 'the book of sand (jorge luis borges)', rating: '8/10' },
                { title: 'shakespeare memory (jorge luis borges)', rating: '8/10' },
                { title: 'artifices (jorge luis borges)', rating: '8/10' },
                { title: 'the aleph (jorge luis borges)', rating: '8/10' },
                { title: 'fictions (jorge luis borges)', rating: '8/10' },
                { title: 'snow crash (neal stephenson)', rating: '8/10' },
            ]
        },
    ],
    backlog: [
        { title: 'the warmth of other suns (isabel wilkerson)' },
        { title: 'the crack-up (f. scott fitzgerald)' },
        { title: 'thoughts of a philosophical fighter pilot (james bond stockdale)' },
        { title: 'courage under fire (james bond stockdale)' },
        { title: 'good to great (jim collins)' },
        { title: 'master and margarita (mikhail bulgakov)' },
        { title: '84, charing cross road (helene hanff)' },
        { title: 'across the universe: the past, present, and future of the crossword puzzle (natan last)' },
        { title: 'all the way to the river: love, loss, and liberation (elizabeth gilbert)' },
        { title: 'ametora: how japan saved american style (w. david marx)' },
        { title: 'arise, england (caroline burt & richard partington)' },
        { title: 'a woven year (jessie mordine young)' },
        { title: 'back from the brink: inside the nypd and new york city’s extraordinary 1990s crime drop (peter moskos)' },
        { title: 'being there (jerzy kosinski)' },
        { title: 'breakneck: china’s quest to engineer the future (dan wang)' },
        { title: 'cable cowboy: john malone and the rise of the modern cable business (mark robichaux)' },
        { title: 'hagakure (yamamoto tsunetomo)' },
        { title: 'humankind (rutger bregman)' },
        { title: 'hyperion cantos (dan simmons)' },
        { title: 'index, a history of the: a bookish adventure from medieval manuscripts to the digital age (dennis duncan)' },
        { title: 'lucky by design (judd b. kessler)' },
        { title: 'lonesome dove (larry mcmurtry)' },
        { title: 'michelangelo: the artist, the man and his times (william e. wallace)' },
        { title: 'murder in the house of omari (taku ashibe)' },
        { title: 'not according to plan: filmmaking under stalin (maria belodubrovskaya)' },
        { title: 'originals: how non-conformists move the world (adam grant)' },
        { title: 'ra (qntm)' },
        { title: 'reality transurfing (vadim zeland)' },
        { title: 'sapiens: a brief history of humankind (yuval noah harari)' },
        { title: 'shuna’s journey (hayao miyazaki)' },
        { title: 'simply more: a book for anyone who has been told they’re too much (cynthia erivo)' },
        { title: 'sun and steel (yukio mishima)' },
        { title: 'the chronicles of prydain (lloyd alexander)' },
        { title: 'the collapse of complex societies (joseph tainter)' },
        { title: 'the courage to be disliked (ichiro kishimi & fumitake koga)' },
        { title: 'the machiavellians: defenders of freedom (james burnham)' },
        { title: 'the maniac (benjamín labatut)' },
        { title: 'the prize: the epic quest for oil, money and power (daniel yergin)' },
        { title: 'the scaling era: an oral history of ai, 2019–2025 (dwarkesh patel & gavin leech)' },
        { title: 'the technological republic (alex karp & nicholas w. zamiska)' },
        { title: 'the william lowell putnam mathematical competition 1985–2000: problems, solutions and commentary (kiran s. kedlaya, bjorn - - poonen & ravi vakil)' },
        { title: 'void star (zachary mason)' },
        { title: 'what kind of paradise (janelle brown)' },
        { title: 'when the going was good: an editor’s adventures during the last golden age of magazines (graydon carter)' },
        { title: 'when we cease to understand the world (benjamín labatut)' },
        { title: 'night of the grizzlies (jack olsen)' },
        { title: 'the tiger (john valiant)' },
        { title: 'marriage at sea (sophie elmrist)' },
        { title: 'in the heart of the sea (nathaniel philbrick)' },
        { title: 'the stranger in the woods (michael finkel)' },
        { title: 'the art thief (michael finkel)' },
        { title: 'the black count (tom reiss)' },
        { title: 'the colossus of maroussi (henry miller)' },
        { title: 'invisible man (ralph ellison)' },
        { title: 'notes to john (joan didion)' },
        { title: 'tunel 29 (helena mermer)' },
        { title: 'what makes sammy run (budd shulberg)' },
        { title: 'an economist gets lunch (tyler cowen)' },
        { title: 'american tabloid (james ellroy)' },
        { title: 'autumn in the heavenly kingdom (platt)' },
        { title: 'an area of darkness (naipaul)' },
        { title: 'a maze of death (philip k. dick)' },
        { title: 'the armchair economist (steven landsburg)' },
        { title: 'the age of innocence (edith wharton)' },
        { title: 'anti-intellectualism in american life (richard hofstadter)' },
        { title: 'a fire upon the deep (vernor vinge)' },
        { title: 'the baby on the fire escape (julie phillips)' },
        { title: 'the big short (michael lewis)' },
        { title: 'the black swan (nassim nicholas taleb)' },
        { title: 'the bookshop (penelope fitzgerald)' },
        { title: 'the box (marc levinson)' },
        { title: 'bourgeois virtues & bourgeois dignity (deirdre mccloskey)' },
        { title: 'the british imperial century (parsons)' },
        { title: 'the charthouse of parma (stendhal)' },
        { title: 'book of imaginary beings' },
        { title: 'the confusions of pleasure: commerce and culture in ming china (brook)' },
        { title: 'the critique of practical reason and pure reason (kant)' },
        { title: 'the count of monte cristo (alexandre dumas)' },
        { title: 'the dark forest (liu)' },
        { title: 'determined (robert sapolsky)' },
        { title: 'the divine invasion (philip k. dick)' },
        { title: 'the economic naturalist (robert frank)' },
        { title: 'ethan frome (edith wharton)' },
        { title: 'the fifth season (nk jemisin)' },
        { title: 'the flame throwers (kushner)' },
        { title: 'fahrenheit 451 (ray bradbury)' },
        { title: 'from rebel to ruler (saich)' },
        { title: 'a history of opera (abbate and parker)' },
        { title: 'the hall of uselessness: collected essays (leys)' },
        { title: 'the heart of darkness (joseph conrad)' },
        { title: 'how the scots invented the modern world (arthur herman)' },
        { title: 'the house of mirth (edith wharton)' },
        { title: 'how the british navy shaped the modern world (herman)' },
        { title: 'in praise of commercial culture (tyler cowen)' },
        { title: 'in praise of shadows (junichiro tanizaki)' },
        { title: 'intellectuals and society (thomas sowell)' },
        { title: 'iron kingdom (clark)' },
        { title: 'the idea factory (jon gertner)' },
        { title: 'life and fate (vasily grossman)' },
        { title: 'the last warrior (krepinevich and watts)' },
        { title: 'lights in the tunnel (richard ford)' },
        { title: 'the magic mountain (thomas mann)' },
        { title: 'the merchant of venice (william shakespeare)' },
        { title: 'memories (tony judt)' },
        { title: 'the misbehavior of markets (nassim nicholas taleb)' },
        { title: 'the money culture (lewis)' },
        { title: 'more money than god (sebastian mallaby)' },
        { title: 'the morning star (karl knausgaard)' },
        { title: 'moby-dick (herman melville)' },
        { title: 'the notebook: a history of thinking on paper (roland allen)' },
        { title: 'nudge (richard thaler & cass sunstein)' },
        { title: 'out (natsuo kirino)' },
        { title: 'patrick melrose series (edward st. aubyn)' },
        { title: 'the passage of power (robert caro)' },
        { title: 'the perfect dictatorship (ringen)' },
        { title: 'the power broker (robert caro)' },
        { title: 'the power to compete (mikitani and mikitani)' },
        { title: 'pure human (hayhouse.com)' },
        { title: 'the plot against america (philip roth)' },
        { title: 'the prisoner\'s dilemma (john von neumann)' },
        { title: 'the red and the black (stendhal)' },
        { title: 'the red swan (heilmann)' },
        { title: 'the rising sun (toland)' },
        { title: 'the right stuff (tom wolfe)' },
        { title: 'the second world wars (hanson)' },
        { title: 'the sound and the fury (william faulkner)' },
        { title: 'swann\'s way (marcel proust)' },
        { title: 'the story of a new name (elena ferrante)' },
        { title: 'the story of the lost child (elena ferrante)' },
        { title: 'the threepenny opera (bertolt brecht)' },
        { title: 'the tempest (william shakespeare)' },
        { title: 'the theory of moral sentiments (adam smith)' },
        { title: 'thinking in bets (annie duke)' },
        { title: 'thinking in time (may & neustadt)' },
        { title: 'the underdog (ahern)' },
        { title: 'trust (hernan diaz)' },
        { title: 'two cheers for anarchism (scott)' },
        { title: 'the world as i found it (david duffy)' },
        { title: 'the world that trade created (pomeranz and topik)' },
        { title: 'wuthering heights (emily bronte)' },
        { title: 'winter\'s tale (mark helprin)' },
        { title: '1491 (charles mann)' },
        { title: 'the wind from the sun (arthur c. clarke)' },
        { title: 'montaigne (stefan zweig)' },
        { title: 'raising hare (choe dalton)' },
        { title: 'everything is tuberculosis (john green)' },
        { title: 'the zorg (siddhart kara)' },
        { title: 'marriage at sea (sophie elmhurst)' },
        { title: 'buckley (sam tanenhaus)' },
        { title: 'on character (general stanley mccrystal)' },
        { title: 'augusts (john williams)' },
        { title: 'marriage and morals (bertrand russell)' },
        { title: 'the last of the wine (mary renault)' },
        { title: 'arcadia (tom stoppard)' },
        { title: 'the better angel of our nature (steven pinker)' },
        { title: 'the end of history and the last man (francis fukuyama)' },
        { title: 'the player of games (iiain m. banks)' },
        { title: 'the river of doubt (candice millard)' },
        { title: 'søren kierkegaard\'s books on agape' },
        { title: 'it can’t happen here (sinclair lewis)' },
        { title: 'the anxious generation (jonathan hairy)' },
        { title: 'how to raise kids who aren’t assholes (melinda winner moyer)' },
        { title: 'the obstacles is the way (ryan holiday)' },
        { title: 'alexander hamilton (ron chernow)' },
        { title: 'the art thief (michael finked)' },
        { title: 'the tiger (john valiant)' },
        { title: 'meow (sam austen)' },
        { title: 'the war of the worlds' },
        { title: 'pride and prejudice' },
        { title: 'hamlet' },
        { title: 'paradise lost' },
        { title: 'rainer maria rilke' },
        { title: 'the technological republic' },
        { title: 'grid systems raster system' },
        { title: 'the elements of typographic style' },
        { title: '7 powers: the foundations of business strategy' },
        { title: 'founders at work, jessica livingston' },
        { title: 'uncorruptible, eric ries' },
        { title: 'david william plummer’s books' },
        { title: 'the sovereign individual' },
        { title: 'the great illusion, by norman angell' },
        { title: 'protocols book from ah' },
        { title: 'the road cormac mccaharty' },
        { title: 'the gamer\'s brain: how neuroscience' },
        { title: 'michael saylor\'s curriculum', url: 'https://gist.github.com/von-steinkirch/746bb4dffa5ba4c0e1042c4f822ecf72' },
        { title: 'fear and trembling → the sickness unto death → either/or → the concept of anxiety → works of love (kierkegaard)' },
        { title: 'aristotle’s nicomachean ethics' },
        { title: 'descartes’s the passions of the soul and others' },
        { title: 'hawkins, j. (2021). a thousand brains: a new theory of intelligence. basic books.' },
        { title: 'hawkins, j., & blakeslee, s. (2004). on intelligence. times books.' },
        { title: 'gray, j. a. (2004). consciousness: creeping up on the hard problem' },
        { title: 'penfield, w. (1975). the mystery of the mind' },
        { title: 'harris, s. (2012). free will' },
        { title: 'robert sapolsky, determined: a science of life without free will' },
        { title: 'rust atomics', url: 'https://mara.nl/atomics/' },
        { title: 'in the theater of consciousness: the workspace of the mind by bernard j. baars', url: 'https://books.google.com/books?hl=en&lr=&id=RTpmQkXoUMEC&oi=fnd&pg=PR13&ots=ZnmiwNpWOe&sig=nRGfRhlNN0Zp0lhZMdIl46Sq4c0#v=onepage&q&f=false' },
    ]
};

window.BOOKS_2026 = BOOKS_2026;
